version: '3'
services:
    # Postgress Database
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    # API Server
    api:
        depends_on:
            - postgres
        restart: always
        build: 
            context: ./
            dockerfile: Dockerfile.dev
        image: meghanags/simpleblog_api
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
        ports:
            - '3000:3000'    